{
 "title": "Single Charon Node Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "CHARON",
   "type": "stat",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "1" }
   ]
  },
  {
   "title": "Version Info",
   "type": "table",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "(\n  sum(app_git_commit) by (git_hash)\n)\n   + on(job) group_left(version)\n(\n   0 * sum(app_version) by (version)\n)\n   + on(job) group_left(lock_hash)\n(\n   0 * sum(app_lock_hash) by (lock_hash)\n)"
    }
   ]
  },
  {
   "title": "Charon status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "app_monitoring_readyz" }
   ]
  },
  {
   "title": "Running Since",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dthms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "(time() - app_start_time_secs)", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "Latest Slot",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "core_scheduler_current_slot", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "Number of connected peers",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(p2p_ping_success)" }
   ]
  },
  {
   "title": "Beacon Node Latency (90%)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(app_eth2_latency_seconds_bucket[30s])) by (le,endpoint)) ",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "description": "Host machine's memory usage",
   "gridPos": { "h": 9, "w": 9, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes - node_memory_MemFree_bytes - node_memory_Buffers_bytes - node_memory_Cached_bytes - node_memory_SwapCached_bytes - node_memory_Slab_bytes - node_memory_PageTables_bytes - node_memory_VmallocUsed_bytes",
     "legendFormat": "apps"
    },
    { "expr": "node_memory_Buffers_bytes", "legendFormat": "buffers" },
    { "expr": "node_memory_Cached_bytes", "legendFormat": "cached" },
    { "expr": "node_memory_MemFree_bytes", "legendFormat": "free" },
    { "expr": "node_memory_Slab_bytes", "legendFormat": "slab" }
   ]
  },
  {
   "title": "Peer ping latency (90%)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 7, "x": 17, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(p2p_ping_latency_secs_bucket[30s])) by (le,peer))  ",
     "legendFormat": "{{peer}}"
    }
   ]
  },
  {
   "title": "VALIDATOR",
   "type": "stat",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "1", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Number of validators",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "validator_local_validator_count"
    }
   ]
  },
  {
   "title": "Current Epoch",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "validator_current_epoch" }
   ]
  },
  {
   "title": "Attestations Published",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "validator_beacon_node_published_attestation_total"
    }
   ]
  },
  {
   "title": "Blocks Proposed",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "validator_beacon_node_published_block_total"
    }
   ]
  },
  {
   "title": "Validator Statuses",
   "type": "table",
   "description": "Number of Validators with the given status.",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "validator_local_validator_counts > 0",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Duties Failed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "validator_duties_performed{result=\"failed\"}",
     "legendFormat": "{{type}}"
    }
   ]
  }
 ]
}